name: Dockerrize and Publish on DockerHub
on:
  push:
    branches: [ main ]
jobs:
  build-container:
  name: build docker container image
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Publish on dockerhub
      uses: docker/build-push_action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: salero33/martullo
        tags: latest, ${{ github.run_number }}
